function var_defs3000() 

% 4/16/10 - akelly
% This is a header file of sorts.
% This script sets up global variables for site-specific data and 
% paths for running code.  If towers or directories are moved,
% change the information here and not in the main code.

%% TO DO
%  - Improve meas. height for Soaproot
%  - Put calibration coeffs here
%%

% site-specific info
global sites numSites siteAlt towerStartDates dayShift towerYearStart MVL
global VIsites SonicOrientation MVLVI MVL_Universal sitePress minFlow minPress %towerHeight
% processing parameters
global procInt qTaus tauRefc tauRefh delayRefc delayRefh ParamsCo2 ParamsH2o Delay_estimate_co2 Delay_estimate_h2o Tau_estimate_co2 Tau_estimate_h2o
% computer-specific info
global hostname inputRootDir fastRootDir soilDir dirSep
global mergedRootDir bestRootDir combineRootDir outputFileRootName
global cleanedRootDir dataRootDir filledRootDir
% constants
global scaleHeightc oneAtmc Tc R_mol CpAirc CpH2Oc Mw_da Mw_water
global inputRootDirList
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Site-specific information
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
sites = {'DC_Burn',...
    'DC_LowDes',...
    'DC_Pinyon',...
    'LR_Grass',...
    'LR_Sage',...
    'JamesRes',...
    'P301',...
    'SJER',...
    'Shorthair', ...
    'Soaproot'};

% sites with vegetation indices
VIsites = [1, 1, 1, 1, 1, 1, 0, 1, 0, 0];

%%% Sonic orientation
% SonicOrientation = [305 236 252 85 266 258 270 NaN];
SonicOrientation = [270 270 270 270 270 180 180 270 270 276];

%%% Updated 10/2011 by mgoulden in SiteDetails.xlsx
% includes tower height
siteAlt = [1303.9;...   % GE
            278.9;...   % GE
           1289.3;...  % GE
            477.0;...  
            477.9;...
           1735.5;... 
           2065.9;... % GE
            424.3;...    % GE
           2736.5;...   % GE
           1196.0];  % Greg/GOES

%%% updated by mgoulden 10/2011
%%% replaces the variable measHeight
%towerHeight = [];   % see SiteDetails.xlsx

% estimated minimum IRGA flow rates for an accurate CO2 conc.  
%minFlow = [6; 6.5; 9; 6.5; 6; 7.2; 10.5; 7; 9; 10];

%James flow filter was too strict 
minFlow = [6; 6.5; 9; 6.5; 6; 6.5; 10.5; 7; 9; 10];
%these are estimates as of 11/9/2012
%minPress = [57.5; 55; 55; 65; 63.5; 55; 55;55;55;55]; % determined by 1 second window
minPress = [69; 55; 60; 62; 63.5; 64; 55; 65 ;52;58]; % determined by visual inspecition of low and outliers
%%% check IRGA pressure instead in future

% calibration CO2 concentration
calibCO2Stds = [350.8; 345; 350.8; 347; 353; 355; 357; NaN; 358; NaN]; 
          
towerStartDates = [[datenum(2006,5,6) ...
    datenum(2006,4,23) ...
    datenum(2006,5,18) ...
    datenum(2006,5,10) ...
    datenum(2006,3,28) ...
    datenum(2006,8,12)] - datenum(2006,1,0)...
    (datenum(2008,9,6)- datenum(2008,1,0))...
    (datenum(2009,10,1)- datenum(2009,1,0))...
    (datenum(2009,10,31)- datenum(2009,1,0))...
    (datenum(2010,7,22) - datenum(2010,1,0))];

towerYearStart(1:6) = datenum(2006,1,0) * ones(6,1);
towerYearStart(7)   = datenum(2008,1,0);
towerYearStart(8:9) = datenum(2009,1,0) * ones(2,1);
towerYearStart(10)  = datenum(2010,1,0);

dayShift = towerYearStart - datenum(1990,1,1);

numSites = length(sites);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Processing parameters
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
procInt = 30;  % processing interval in minutes
procInt = procInt/(24*60);  % convert to fractional day

%Delays
%site specific tubing delay estimates 
%Delay_estimate = [1;1;1;1;1;3;9;2;6;5]; % units = [s] - awf
%Delay_estimate_co2 = [0.962;1.403;1.47;1.276;1.24;3.92;9;2;6;5]; % units = [s] - awf
%Delay_estimate_h2o = [1.155;1.592;1.32;1.285;1.897;4.15;9;2;6;5]; % units = [s] - awf

%The Delay_estimate was determined by maximizing the covariance between 
%the wind and co2 or h20 for only a few days.
%I only used observations where stong covariances occurred for periods with
%incoming solar radiation > 0 and removing spiking sonic.
%I used medians to determine the delay

%reprocessed SoCal sites were run with these delays 
Delay_estimate_co2 = [0.962;1.653;1.72;1.276;1.49;4.17;6.75;2.5;4.5;4.75]; % units = [s] - awf 7/16/2012
Delay_estimate_h2o = [1.405;2.092;1.82;2.535;2.647;4.65;7.25;2.75;4.5;5]; % units = [s] - awf 7/16/2012

%next run use these  11/14/2012 -awf
%Delay_estimate_co2 = [0.962;1.903;1.97;1.276;.74;4.42;5.75;2.5;4.5;4.75]; % units = [s] 11/14/2012
%Delay_estimate_h2o = [1.655;2.592;2.32;3.535;2.397;5.15;6.5;2.75;4.5;5]; % units = [s] 11/14/2012 

%I used CO2 uptake periods
%I removed spiking sonic, bad irga, ust <.3, flow below min flow (see
%above), and light (pyr) periods below 0 (i.e. high light
%periods)


% time constant calculation set to happen 2 times per day
% set to 'no' for no calculation of time constants
qTaus='TwoPerDay';

%tauRefc = 0.35;    
%tauRefh = 0.42;

%These Taus were found by maximizing the correlation between degraded
%temperature and the co2 flux
%Tau_estimate_co2 = [3.6791;6.0784;3.6915;5.3712;4.931;5.3548];
%Tau_estimate_h2o = [4.1298;5.6424;4.3613;8.334;7.9295;5.9843];


%new Tau estimate - awf 9/5/2012
%The Tau for Sierra sites is just a guess - no estimates have been made
Tau_estimate_co2 = [3.6;5;4;3.7;3.3;5.4;4.5;5.2;4.4;4.8];
Tau_estimate_h2o = [4.2;5.4;5;10;7.65;6.9;6.4;6.5;6.55;6.8];

%Next run use these -11/14/2012 awf
%Tau_estimate_co2 = [3.6;5.2;4;3.7;3.3;5.4;4.5;5.2;4.4;4.8]; % units = [s] 11/14/2012 
%Tau_estimate_h2o = [4.2;5.5;5;10;7.6;6.9;6.3;6.5;6.7;6.8]; % units = [s] 11/14/2012

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Computer-specific information
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Name of the GOES computer
%%% does this do anything?
% GOEScomp = 'Discostu';

% grab the host name of the machine running the computer
[ret, hostname] = system('hostname');
if ret ~= 0,
   if ispc
      hostname = getenv('COMPUTERNAME');
   else
      hostname = getenv('HOSTNAME');
   end
end
hostname = lower(hostname);

%%% set paths, could be host dependent eventually?
%%% Also, maybe have a preference for directory separator?

[x, user] = system('whoami');
user = strtrim(user);

%%% if strcmp(user, 'anne')
%    inputRootDir  = '/Users/anne/Documents/California/';
%    outputRootDir = '/Users/anne/Documents/Calfornia/data_analysis/';
%    dirSep        = '/';
%else


%This is just to run a long job on 5/24/2012- Tau
    %inputRootDirList = {'C:\towerData\Tau\T1\';...
    %'C:\towerData\Tau\T2\';...
    %'C:\towerData\Tau\T3\';...
    %'C:\towerData\Tau\T4\'};

    %This is to run the job on 7/03/2012 -Tau2
    %inputRootDir = 'C:\towerData\Tau\TauThird\T\'; Tau3
    inputRootDir  = '..\';
    fastRootDir = '..\fast\';
    dirSep        = '\';
    fastRootDir = [inputRootDir 'fast' dirSep];
    mergedRootDir = [inputRootDir 'merged' dirSep];
    bestRootDir   = [inputRootDir 'best'   dirSep];
    combineRootDir = [inputRootDir 'combined' dirSep];
    cleanedRootDir = [inputRootDir 'cleaned' dirSep];
    webRootDir    = [inputRootDir 'webpage' dirSep];
    dataRootDir   = [webRootDir 'Data' dirSep];
    filledRootDir = [inputRootDir 'filled' dirSep];
    goesRootDir   = [inputRootDir 'goes' dirSep];
    outputFileRootName = 'Fluxes_';
    soilDir = [inputRootDir 'SoilMoisture' dirSep];

%end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Set constants
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Tc            = 273.15;   % K
scaleHeightTc = Tc + 20;  % K
gc            = 9.8;      % m s^-2
Rc            = 287;      % J K^-1 kg^-1
Rgasc         = 0.08206;  % L atm K^-1 mol^-1
CpAirc        = 1004.67;  % J K^-1 kg^-1
CpH2Oc        = 1875;     % J K^-1 kg^-1
Mwairc        = 0.0297;   % kg mol^-1
MwH2Oc        = 0.018;    % kg mol^-1
scaleHeightc  = Rc * scaleHeightTc / gc;
oneAtmc       = 101.325;  % kPa
R_mol         = 8.314;    %J K-1 Mol-1
Mw_da         = 28.966;   % g/mol
Mw_water      = 18.01 ;   % g/mol

sitePress = oneAtmc .* exp(-1 .* siteAlt ./ (Rc .* scaleHeightTc ./ gc));


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Set up the master variable list (MVL)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%Universal 
MVL_Universal = {'Counter';...
    'Day of Experiment (decimal)';...
    'HHMM';...
    'U mean, East to West';...
    'V mean, North to South';...
    'W';...
    'Ts';...
    'var(u) along wind';...
    'var(v) cross wind';...
    'var(w)';...
    'var(Ts)';...
    'Skewness(u) along wind';...
    'Skewness(v) cross wind';...
    'Skewness(w)';...
    'Skewness(Ts)';...
    'kurtosis(u) along wind';...
    'kurtosis(v) cross wind';...
    'kurtosis(w)';...
    'kurtosis(Ts)';...
    'USTAR';...
    'Wind Dir (met)';...
    'COV(UW) ROT';...
    'COV(VW) ROT';...
    'COV(UV) ROT';...
    'COV(UT)';...
    'COV(VT)';...
    'COV(WT)';...
    'H SENSIBLE calculated with dry air density and dried sonic temperature (W/M2)';'HLATENT (W/M2)';...
    'H BUOYANT (from sonic) (W/M2)';...
    'CO2 Closed Path MIN (PPM)';...
    'CO2 Closed Path MAX (PPM)';...
    'CO2 Closed Path MEDIAN (PPM)';...
    'CO2 Closed Path MEAN (PPM)';...
    'CO2 Closed Path STD (ppm)';...
    'CO2 Closed Path SKEW';...
    'CO2 Closed Path KURT';...
    'H2O Closed Path MIN (mmol/mol)';...
    'H2O Closed Path MAX (mmol/mol)';...
    'H2O Closed Path MEDIAN (mmol/mol)';...
    'H2O Closed Path MEAN (mmol/mol)';...
    'H2O Closed Path STD (mmol/mol)';...
    'H2O Closed Path SKEW';...
    'H2O Closed Path KURT';...
    'CO2 Closed Path FLUX, HF Correction using sonic temperature, (umol/m2/s)';...
    'H2O Closed Path FLUX, HF Correction using sonic temperature, (mmol/m2/s)';...
    'RHO DRY Closed Path (mol/M3)';...
    'RHO H2O VAP Closed Path (mol/M3)';...
    'Tau CO2 using max cov (sec)';...
    'Tau CO2 actually used for HF correction (sec)';...
    'Tau H2O using max cov (sec)';...
    'Tau H2O actually used for HF correction (sec)';...
    'Delay CO2 using max cov (sec)';...
    'Delay CO2 actually used (sec)';...
    'Delay H2O using max cov (sec)';...
    'Delay H2O actually used (sec)';...
    'Gain for co2 flux using sonic temperature flux and Shaw Model tau';...
    'Gain for h2o flux using sonic temperature flux and Shaw Model tau';...
    'Uz_Uz_2';...
    'Uz_Ux_2';...
    'Uz_Uy_2';...
    'Uz_co2_2';...
    'Uz_h2o_2';...
    'Uz_Ts_2';...
    'Ux_Ux_2';...
    'Ux_Uy_2';...
    'Ux_co2_2';...
    'Ux_h2o_2';...
    'Ux_Ts_2';...
    'Uy_Uy_2';...
    'Uy_co2_2';...
    'Uy_h2o_2';...
    'Uy_Ts_2';...
    'co2_co2_2';...
    'co2_h2o_2';...
    'co2_Ts_2';...
    'h2o_h2o_2';...
    'h2o_Ts_2';...
    'Ts_Ts_2';...
    'Ux_1_Avg';...
    'Uy_1_Avg';...
    'Uz_1_Avg';...
    'Ts_1_Avg';...
    'co2_molar_Avg';...
    'h2o_molar_Avg';...
    'netrad_Avg';...
    'pyrr_in_Avg';...
    'pyrr_out_Avg';...
    'par_in_Avg';...
    'par_out_Avg';...
    'Red_in_Avg';...
    'NIR_in_Avg';...
    'Red_out_Avg';...
    'NIR_out_Avg';...
    'NDVI_Avg';...
    't_hmp_Avg';...
    'rh_hmp_Avg';...
    'e_Avg';...
    'h2o_hmp_Avg';...
    'e_sat_Avg';...
    'T_107_Avg';...
    'rain_Tot';...
    'tc_5000_Avg';...
    'batt_5000_Avg';...
    'battbank_V_Avg';...
    'panel_V_Avg';...
    'system_V_Avg';...
    'irgatemp_Avg';...
    'irgapress_Avg';...
    'irgaready_Avg';...
    'irgaflow_Avg';...
    'boxtemp_low_Avg';...
    'battboxtemp_Avg';...
    'batt_5000_Min';...
    'battbank_V_Min';...
    'system_V_Min';...
    'irgatemp_Min';...
    'irgapress_Min';...
    'irgaflow_Min';...
    'irgaready_Max';...
    'co2zero';...
    'h2ozero';...
    'flowzero';...
    'co2span';...
    'h2ospan';...
    'flowspan';...
    'Fwd_Pwr';...
    'Rfl_Pwr';...
    'Batt_4a';...
    'GPS_time';...
    'tube_delay';...
    'n_Tot';...
    'csat_warnings_Tot';...
    'irga_warnings_Tot';...
    'del_T_f_1_Tot';...
    'track_f_1_Tot';...
    'amp_h_f_1_Tot';...
    'amp_l_f_1_Tot';...
    'low12V_5000_Tot';...
    'watchdog_500_Tot';...
    'Temp_alert_Tot';...
    'Red_alert_Tot';...
    'Yellow_alert_Tot';...
    'Pump_on_Tot';...
    'IRGA_on_Tot';...
    'Tower_on_Tot';...
    'Samp_Cal_Tot';...
    'CO2_zero_Tot';...
    'Ux_1_Std';...
    'Uy_1_Std';...
    'Uz_1_Std';...
    'Ts_1_Std';...
    'co2_molar_Std';...
    'h2o_molar_Std';...
    'netrad_Std';...
    'pyrr_in_Std';...
    'pyrr_out_Std';...
    'par_in_Std';...
    'par_out_Std';...
    't_hmp_Std';...
    'rh_hmp_Std';...
    'Red_in_Std';...
    'NIR_in_Std';...
    'Red_out_Std';...
    'NIR_out_Std';...
    'T_107_Std';...
    'tc_5000_Std';...
    'batt_5000_Std';...
    'battbank_V_Std';...
    'panel_V_Std';...
    'system_V_Std';...
    'irgatemp_Std';...
    'irgapress_Std';...
    'irgaready_Std';...
    'irgaflow_Std';...
    'NGOOD_SONIC';...
    'NGOOD_SONIC_AND_IRGA';...
    'SECONDS';...
    'NANOSECONDS';...
    'Ntemp';...
    'Nco2';...
    'Nh2o';...
    'Tau_c_max';...
    'Tau_h2o_max'};

